export { default as IInput } from "./input"
export { default as IButton } from "./button"
export { default as ITitle } from "./title"
export { default as IPickerInput } from "./pickerInput"
export { default as ILabel } from "./label"
export { default as IPureButton } from "./pureButton"
